stages:
  - test

job_test:
  stage: test
  tags:
    - github
  image: registry.cn-hangzhou.aliyuncs.com/tik/node:tik
  cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  only:
    - master
  script:
    - ls
    - npm i
    - npm test